version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: vhub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vhub_db
      MYSQL_USER: rich
      MYSQL_PASSWORD: rich@fang#3um!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vhub-web
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - VHUB_DATABASES_HOST=mysql
    volumes:
      - ./config:/app/config

volumes:
  mysql_data: